- name: Clean Load Balancers
  hosts: lb_servers
  gather_facts: no
  tasks:
    - name: Remove packages
      yum:
        name:
          - haproxy
          - socat
        state: absent
    - set_fact:
        firewall_rules:
          - port: 80/tcp
          - zone: internal
            port: 8008/tcp
          - zone: internal
            source: 172.25.250.10


- name: Clean Web Servers
  hosts: web_servers
  gather_facts: no
  tasks:
    - name: Remove packages
      yum:
        name:
          - httpd
          - php
          - git
          - php-mysqlnd
        state: absent
    - set_fact:
        firewall_rules:
          - zone: internal
            port: 8008/tcp
          - zone: internal
            source: 172.25.250.10
    - name: Remove /var/www/html files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
        - /var/www/html/index.php


- name: Clean Firewall rules
  hosts: lb_servers, web_servers
  tasks:
    - name: Ensure Firewall Sources Configuration
      firewalld:
        source: "{{ item.source | default(omit) }}"
        zone: "{{ item.zone | default(omit) }}"
        permanent: yes
        state: 'disabled'
        service: "{{ item.service | default(omit) }}"
        port: "{{ item.port | default(omit) }}"
      loop: "{{ firewall_rules }}"

    - name: reload firewalld
      service:
        name: firewalld
        state: reloaded

