---

- name: Ensure Apache is deployed
  hosts: web_servers
  force_handlers: True
  gather_facts: no

  roles:
    # Apache-specific firewall rules are defined
    # in the 'apache_firewall_rules' variable
    - role: apache

